package com.example.imageuploadingpractice.converters;

import com.example.imageuploadingpractice.commands.UserCommand;
import com.example.imageuploadingpractice.domain.UserEntity;
import lombok.extern.slf4j.Slf4j;
import org.springframework.core.convert.converter.Converter;
import org.springframework.lang.Nullable;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

@Component
@Slf4j
public class UserCommandToUserEntity implements Converter<UserCommand, UserEntity> {

    @Override
    @Transactional
    @Nullable
    public UserEntity convert(UserCommand source) {

        log.info("I'm in converter");

        if(source==null){
            log.error("I'm in converter: source is null");
            return null;
        }

        UserEntity userEntity = new UserEntity();
        //todo no access to user entity id from command, value is generated by framework

        userEntity.setFirstName(source.getFirstName());
        userEntity.setLastName(source.getLastName());
        userEntity.setEmailAddress(source.getEmailAddress());
        userEntity.setImage(source.getImage());

        return userEntity;
    }
}
